# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e761100b7908886228f8e5217ee3a7553eef3d2c2cebf8257b5b7264b7d0985161d75e3f3843ba1911306ea5070d77b3875f6ae48274dc1ff2398a402d183b2

test:
  secret_key_base: 090125bee62db860f21547c0684a8e72610f2feba56dc8688c8dce43bf88d01101d24d979b748a724894a5e27358fe254e521e51cb6c1f447915c182fcf3cb5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
